default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 20000 # Increase timeout to 20 seconds

development:
  <<: *default
  database: db/development.sqlite3
